### PR TITLE
Translate README to English (#4, #5)

### LINKED ISSUE #4: Translate README to english
Translate the README to english to address english speaking contributors. 

This is one of the tasks from the team vote of 25th March 2020. With the development of the website mycoradar.eu, which is also to be written in English, English-speaking interested parties may be increasingly addressed

### PR DESCRIPTION
**Pull request by rfuehrer**
this PR implements issues

Fixes #4 
Fixes #5 

(with credit to @dehesselle )

### CODE REVIEW

**Comment by dehesselle** [comment]
I'm being pedantic with my review. I think we need at least one more iteration since I have collected quite a few remarks. I haven't cross-referenced everything between the English and the German version yet, that is something left to be done in the next iteration. So my focus is mainly the English version. (You'll probably have to fix them both at the same time.)

- Maybe turn "#WirVsVirus" into a link to the hashtag on Twitter? e.g.  https://twitter.com/hashtag/wirvsvirus?lang=de
- typo: "With the solution we provide, all devices in the environment are logged by **your** own device."
- lose "service": "From a central server ~service~, device IDs..."
- I don't like the "(!!!)". Text is already bold, please lose the exclamation marks.
- missing asterisks: you wanted to make something bold in "no display of device IDs" but the closing asterisks are missing
- Replace "We are happy about forks..." with something like "We gladly accept your contributions / pull requests."
- Authors section: maybe sort by name since there is no implied ranking?
- Authors section: is "baking" really a common term used in software development? (I Googled "software baking" and don't get relevant results.)
- After having read it multiple times, I think the "patting ourselves on the back because we are so graciously offering this under MIT license" really needs to go. You can keep everything but the first sentence. To be clear: Begin with "We want to help fight this..." and lose the sentence before.
- Lose the "A support can be done..." sentence. We've already explained above that we gladly accept contributions.

**Comment by rfuehrer** [comment]
I agreee with your comments and have implemented all bullets.

**Comment by dehesselle** [comment]
Have a last look at the following and then you can merge away:

- tagline (first line after top level heading) different between German and English version
- remove "development status" from German version
- WirVsVirus is not a link in German version
- two bullet points below "Our idea" are missing the bold emphasis in German version
- syntax error in the link to the architecture picture in English version (it's missing the leading exclamation mark)
- "activated Bluetooth" missing in Client components in German version
- remove "(!!!)" in German version
- author list not sorted in both versions (not a requirement, I'm just noting because you didn't disagree with me on this)
- "Für uns steht außer Frage" sentence still present in German version
- privacy section: "**no display of device iDs or location of third-party devices!" is still missing closing asterisks for bold emphasis

**Comment by rfuehrer** [comment]
- tagline (first line after top level heading) different between German and English version - fixed
- remove "development status" from German version - fixed
- WirVsVirus is not a link in German version -fixed
- two bullet points below "Our idea" are missing the bold emphasis in German version - fixed
- syntax error in the link to the architecture picture in English version (it's missing the leading exclamation mark) - fixed
- "activated Bluetooth" missing in Client components in German version
- remove "(!!!)" in German version - fixed
- author list not sorted in both versions (not a requirement, I'm just noting because you didn't disagree with me on this) - Ladies first ;), but I agree with you
- "Für uns steht außer Frage" sentence still present in German version - fixed
- privacy section: "**no display of device iDs or location of third-party devices!" is still missing closing asterisks for bold emphasis - fixed

**Pull request merged**
